name: jagoan_inggris
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.24.0 # Disarankan versi lebih baru untuk tahun 2026

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  model_viewer_plus: ^1.7.0 
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/models/avatar_default.glb
    - assets/models/teacher.glb
    # Perbaikan jalur jika folder Anda adalah assets/images/
    - assets/images/icon_body.png
    - assets/images/icon_wings.png
    - assets/images/icon_weapon.png