// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCicfG60qfark3QdQVNPqE5j-cULReKM3U',
    appId: '1:753223088412:web:884ea859cf0fd70682a2d9',
    messagingSenderId: '753223088412',
    projectId: 'jagoan-inggris',
    authDomain: 'jagoan-inggris.firebaseapp.com',
    storageBucket: 'jagoan-inggris.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRkiZY7AqXZQtYUKsdAEW9fqH396xzfoo',
    appId: '1:753223088412:android:f6bceab142fed25582a2d9',
    messagingSenderId: '753223088412',
    projectId: 'jagoan-inggris',
    storageBucket: 'jagoan-inggris.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO4Uh6IW65ho-L0meUbMoTdczBFe8MmG4',
    appId: '1:753223088412:ios:235c597ee65ce2d282a2d9',
    messagingSenderId: '753223088412',
    projectId: 'jagoan-inggris',
    storageBucket: 'jagoan-inggris.firebasestorage.app',
    iosBundleId: 'com.example.jagoanInggris',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCO4Uh6IW65ho-L0meUbMoTdczBFe8MmG4',
    appId: '1:753223088412:ios:235c597ee65ce2d282a2d9',
    messagingSenderId: '753223088412',
    projectId: 'jagoan-inggris',
    storageBucket: 'jagoan-inggris.firebasestorage.app',
    iosBundleId: 'com.example.jagoanInggris',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCicfG60qfark3QdQVNPqE5j-cULReKM3U',
    appId: '1:753223088412:web:0d13781cfd0e9df282a2d9',
    messagingSenderId: '753223088412',
    projectId: 'jagoan-inggris',
    authDomain: 'jagoan-inggris.firebaseapp.com',
    storageBucket: 'jagoan-inggris.firebasestorage.app',
  );
}
